const colors = {
  light: {
    text: "#0f172a",
    tint: "#2563eb",
    background: "#f8fafc",
    foreground: "#0f172a",
    card: "#ffffff",
    cardForeground: "#0f172a",
    primary: "#2563eb",
    primaryDark: "#1d4ed8",
    primaryForeground: "#ffffff",
    secondary: "#eff6ff",
    secondaryForeground: "#1e40af",
    muted: "#e8f0fe",
    mutedForeground: "#64748b",
    accent: "#eff6ff",
    accentForeground: "#1e40af",
    success: "#16a34a",
    successLight: "#f0fdf4",
    successForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    warning: "#f59e0b",
    warningLight: "#fffbeb",
    border: "#e2e8f0",
    input: "#e2e8f0",
    ring: "#2563eb",
    surfaceElevated: "#ffffff",
    tabBar: "#ffffff",
  },
  radius: 10,
};

export default colors;
