// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kpi-cards-320.tsx": () => import("../components/mockups/kpi-cards-320.tsx")
};
